### ISSUE TITLE
v10 update OTA failure?

### ISSUE THREAD

**Issue by JWhiteIV** [justcallmekoko/justcallmekoko#1]
Is this a known issue? How can I restore to the shipped firmware version and try again. Currently, device does not boot.

**Comment by justcallmekoko** [comment]
Please use the provided issue template. I don't actually know what issue you're having so I can't tell you if this is a known issue or not

**Comment by JWhiteIV** [comment]
Ok, I simply have a black screen after updating with the latest firmware OTA.  Will locate the issue template and fill in the details. 

Order 362637
ESP32 Marauder
Item# 18561

**Comment by justcallmekoko** [comment]
Make sure you also post this under the [ESP32 Marauder](https://github.com/justcallmekoko/ESP32Marauder) repo
